name: auto-backup
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Runs daily at 1:00
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  backup:
    name: Daily Backup
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v2
        with:
          ref: auto_backup_1
      - run: |
          # The config setup uses default Git tokens for the user/pw.
          git config user.name github-actions
          git config user.email github-actions@github.com
          # Rebase takes any changes from master and applies them to auto_backup_1
          # If there's no changes, nothing happens
          # Use fetch to see the rest of the repo, then set the upstream. Rebase, pull in any changes, then push the rebase to update auto_backup_1.
          # Effectively, this grabs any changes from master, pulls them to the local job, then pushes them to the real repo.
          git fetch origin
          git branch --set-upstream-to origin/auto_backup_1
          git rebase -s ours origin/master
          git merge -s ours --allow-unrelated-histories origin/auto_backup_1
          git push